runtime: php55
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic   # default value
  max_idle_instances: automatic   # default value
  min_pending_latency: 30ms       # default value
  max_pending_latency: automatic
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
